services:
  db:
    image: postgis/postgis:16-3.4
    container_name: geo-areas-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: azerbijal324
      POSTGRES_DB: geo_mapa_app
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d geo_mapa_app"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
